// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tags

import (
	"jesusmail-core/api/tags"
)

type ControllerV1 struct{}

func NewV1() tags.ITagsV1 {
	return &ControllerV1{}
}
